### PR TITLE
remove linefeed and build-in kernel config parameter from boot parameter

### PR DESCRIPTION
**Pull request by fehlix**

### CODE REVIEW

**Comment by AdrianTM** [comment]
I see only the changelog being modified, are you sure you added the file you modified? 
https://github.com/MX-Linux/mx-snapshot/pull/19/files

**Comment by AdrianTM** [comment]
I already remove BOOT_IMAGE stuff here: https://github.com/MX-Linux/mx-snapshot/blob/main/settings.cpp#L679-L687

**Comment by fehlix** [comment]
> I already remove BOOT_IMAGE stuff here: https://github.com/MX-Linux/mx-snapshot/blob/main/settings.cpp#L679-L687

Does not work for when booted live . So I moved it "up"  to remove it always. ALs it is always the first, after removing any buildin parameters, so the removal will now only remove when it is the first "added by grub"

**Comment by AdrianTM** [comment]
I didn't remove it when booted live on purpose because it's not a default live option, I could change this to filter that out too. 

boot_options = live ? readKernelOpts() : filterOptions(readKernelOpts());

**Comment by fehlix** [comment]
> I didn't remove it when booted live on purpose because it's not a default live option, I could change this to filter that out too.
> 
> boot_options = live ? readKernelOpts() : filterOptions(readKernelOpts());

BOOT_IMAGE= needs to get removed as it is automatically added the same as build in, hence to move it into the "always" place.
Also in case a user want to "play" with it we only remove it as the first added by grub, with the ^-anchor.

**Pull request merged**
